---
# tasks file for common

- name: Change repository Ubuntu 20.04
  copy:
    src: sources.list
    dest: /etc/apt/
    backup: yes

- name: Update repository and Upgrade packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400 # update unless last update was no longer then 1 day ago
    autoremove: yes
    autoclean: yes

- name: Setup timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: add several users
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    password: "{{ item.pass }}"
    shell: /bin/bash
  loop:
 
- name: create key directory
  action: file path=/etc/ssh/authorized_keys state=directory
    owner=0 group=0 mode=0755

- name: upload user key
  action: copy src=authorized_keys/{{ item }}
    dest=/etc/ssh/authorized_keys/
    owner=0 group=0 mode=644
  with_items: 
    - ansible

- name: sshd configuration file update
  template: src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0644
    validate='/usr/sbin/sshd -T -f %s'
  notify:
  - restart sshd
